### ISSUE TITLE
Request: create GH Release Notes text for the CLI releases

### ISSUE THREAD

**Issue by ericsampson** [seaplane-io/seaplane#343]
The action that y'all are using to create the CLI GH releases allows for the creation of GH release note descriptions by supplying either a text string or a file. 
Having release notes in the GH releases is really nice for end users. (in addition to the current changelog)

The GH Action also supports using the [GH Release Note auto-creation mechanisms](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes), which might be a handy way to implement this feature request.

👋❤️

**Comment by kbknapp** [comment]
Eric! 🎉 

That's an excellent suggestion, I'll look into this when I prep the next release! At a minimum I'd love to include the most recent version form the changelog at a minimum. I've used tools like [`clog`](https://github.com/clog-tool/clog-cli) heavily before but they require all contributors to follow the format which can be difficult.

**Comment by ericsampson** [comment]
@kbknapp yeah exactly!

I happened to notice a new release in my GH notifications and it triggered this thought, I forgot to unsubscribe from this repo notifications 😅

Cheers
